name: 'ЁЯТм шоишо║'
description: 'х╝АхзЛф╕Аф╕кшоишо║'
title: '[шоишо║] шоишо║цаЗщвШ'
labels: ['discussion']
assignees: []
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: 'шоишо║хЖЕхо╣'
      description: 'шп╖цППш┐░ф╜ацГ│шоишо║чЪДшпЭщвШуАБцГ│ц│ХцИЦщЧощвШя╝ИхПпчЫ┤цОецЛЦцЛ╜цЦЗф╗╢щЩДхКацИкхЫ╛цИЦщУ╛цОея╝Й'
      placeholder: |
        шоишо║ф╕╗щвШя╝Ъ...
        чЫ╕хЕ│щУ╛цОея╝Ъ...
        цИкхЫ╛я╝Ъ...
