import { Contact } from './types';

export const MOCK_CONTACTS: Contact[] = [
  {
    id: '1',
    name: 'rag',
    avatar: '',
    title: '后端开发工程师',
    department: '技术部',
    phone: '+86 138-0000-0001',
    email: 'rag@docflow.com',
    status: 'online',
    isStarred: false,
    isManager: true,
    bio: '负责后端架构设计和核心功能开发',
    tags: ['技术', '后端', 'Python'],
    isExternal: false,
  },
  {
    id: '2',
    name: '北极星',
    avatar: '',
    title: '产品经理',
    department: '产品部',
    phone: '+86 138-0000-0002',
    email: 'polaris@docflow.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '专注于产品规划和用户体验设计',
    tags: ['产品', 'UX'],
    isExternal: false,
  },
  {
    id: '3',
    name: '党乙豪',
    avatar: '',
    title: '前端开发工程师',
    department: '技术部',
    phone: '+86 138-0000-0003',
    email: 'dang@docflow.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '专注于前端开发和用户界面设计',
    tags: ['前端', 'React', 'TypeScript'],
    isExternal: false,
  },
  {
    id: '4',
    name: '邓浩',
    avatar: '',
    title: 'UI设计师',
    department: '设计部',
    phone: '+86 138-0000-0004',
    email: 'deng@docflow.com',
    status: 'offline',
    isStarred: true,
    isManager: false,
    bio: '负责产品视觉设计和交互设计',
    tags: ['设计', 'UI/UX'],
    isExternal: false,
  },
  {
    id: '5',
    name: 'Moment',
    avatar: '',
    title: 'CEO',
    department: '管理层',
    phone: '+86 138-0000-0005',
    email: 'moment@docflow.com',
    status: 'online',
    isStarred: true,
    isManager: true,
    bio: '负责公司整体战略规划和管理',
    tags: ['管理', '战略'],
    isExternal: false,
  },
  {
    id: '6',
    name: '何夫平',
    avatar: '',
    title: '测试工程师',
    department: '技术部',
    phone: '+86 138-0000-0006',
    email: 'he@docflow.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责产品质量保证和自动化测试',
    tags: ['测试', '质量保证'],
    isExternal: false,
  },
  {
    id: '7',
    name: '胡璐鑫',
    avatar: '',
    title: '运营经理',
    department: '运营部',
    phone: '+86 138-0000-0007',
    email: 'hu@docflow.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '负责产品运营和用户增长',
    tags: ['运营', '增长'],
    isExternal: false,
  },
  {
    id: '8',
    name: '小雨',
    avatar: '',
    title: '市场专员',
    department: '市场部',
    phone: '+86 138-0000-0008',
    email: 'rain@docflow.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责市场推广和品牌建设',
    tags: ['市场', '推广'],
    isExternal: false,
  },
  {
    id: '9',
    name: 'KingYen',
    avatar: '',
    title: '全栈开发工程师',
    department: '技术部',
    phone: '+86 138-0000-0009',
    email: 'king@docflow.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '负责全栈开发和技术架构',
    tags: ['全栈', 'Node.js', 'React'],
    isExternal: false,
  },
  {
    id: '10',
    name: 'Ting',
    avatar: '',
    title: '数据分析师',
    department: '数据部',
    phone: '+86 138-0000-0010',
    email: 'ting@docflow.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '负责数据分析和业务洞察',
    tags: ['数据', '分析'],
    isExternal: false,
  },
  {
    id: '11',
    name: 'Usena',
    avatar: '',
    title: 'HR经理',
    department: '人力资源部',
    phone: '+86 138-0000-0011',
    email: 'usena@docflow.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责人才招聘和员工关系管理',
    tags: ['HR', '招聘'],
    isExternal: false,
  },
  {
    id: '12',
    name: '万永健',
    avatar: '',
    title: '财务总监',
    department: '财务部',
    phone: '+86 138-0000-0012',
    email: 'wan@docflow.com',
    status: 'offline',
    isStarred: false,
    isManager: true,
    bio: '负责财务管理和成本控制',
    tags: ['财务', '管理'],
    isExternal: false,
  },
  {
    id: '13',
    name: '张涵文',
    avatar: '',
    title: '客户经理',
    department: '销售部',
    phone: '+86 138-0000-0013',
    email: 'zhang@docflow.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责客户关系维护和销售',
    tags: ['销售', '客户'],
    isExternal: false,
  },
  {
    id: '14',
    name: '外部顾问',
    avatar: '',
    title: '技术顾问',
    department: '外部',
    phone: '+86 138-0000-0014',
    email: 'consultant@external.com',
    status: 'offline',
    isStarred: false,
    isManager: false,
    bio: '提供技术咨询服务',
    tags: ['顾问', '外部'],
    isExternal: true,
  },
  {
    id: '15',
    name: '合作伙伴',
    avatar: '',
    title: '商务经理',
    department: '外部',
    phone: '+86 138-0000-0015',
    email: 'partner@external.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '战略合作伙伴',
    tags: ['合作', '外部'],
    isExternal: true,
  },
];
