import { Contact } from './types';

export const MOCK_CONTACTS: Contact[] = [
  {
    id: '1',
    name: '张三',
    avatar: '',
    title: '后端开发工程师',
    department: '技术部',
    phone: '+86 138-1234-5678',
    email: 'zhangsan@example.com',
    status: 'online',
    isStarred: false,
    isManager: true,
    bio: '负责后端架构设计和核心功能开发',
    tags: ['技术', '后端', 'Python'],
    isExternal: false,
  },
  {
    id: '2',
    name: '李四',
    avatar: '',
    title: '产品经理',
    department: '产品部',
    phone: '+86 138-2345-6789',
    email: 'lisi@example.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '专注于产品规划和用户体验设计',
    tags: ['产品', 'UX'],
    isExternal: false,
  },
  {
    id: '3',
    name: '王五',
    avatar: '',
    title: '前端开发工程师',
    department: '技术部',
    phone: '+86 138-3456-7890',
    email: 'wangwu@example.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '专注于前端开发和用户界面设计',
    tags: ['前端', 'React', 'TypeScript'],
    isExternal: false,
  },
  {
    id: '4',
    name: '赵六',
    avatar: '',
    title: 'UI设计师',
    department: '设计部',
    phone: '+86 138-4567-8901',
    email: 'zhaoliu@example.com',
    status: 'offline',
    isStarred: true,
    isManager: false,
    bio: '负责产品视觉设计和交互设计',
    tags: ['设计', 'UI/UX'],
    isExternal: false,
  },
  {
    id: '5',
    name: '孙七',
    avatar: '',
    title: 'CEO',
    department: '管理层',
    phone: '+86 138-5678-9012',
    email: 'sunqi@example.com',
    status: 'online',
    isStarred: true,
    isManager: true,
    bio: '负责公司整体战略规划和管理',
    tags: ['管理', '战略'],
    isExternal: false,
  },
  {
    id: '6',
    name: '周八',
    avatar: '',
    title: '测试工程师',
    department: '技术部',
    phone: '+86 138-6789-0123',
    email: 'zhouba@example.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责产品质量保证和自动化测试',
    tags: ['测试', '质量保证'],
    isExternal: false,
  },
  {
    id: '7',
    name: '吴九',
    avatar: '',
    title: '运营经理',
    department: '运营部',
    phone: '+86 138-7890-1234',
    email: 'wujiu@example.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '负责产品运营和用户增长',
    tags: ['运营', '增长'],
    isExternal: false,
  },
  {
    id: '8',
    name: '郑十',
    avatar: '',
    title: '市场专员',
    department: '市场部',
    phone: '+86 138-8901-2345',
    email: 'zhengshi@example.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责市场推广和品牌建设',
    tags: ['市场', '推广'],
    isExternal: false,
  },
  {
    id: '9',
    name: '钱十一',
    avatar: '',
    title: '全栈开发工程师',
    department: '技术部',
    phone: '+86 138-9012-3456',
    email: 'qianshiyi@example.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '负责全栈开发和技术架构',
    tags: ['全栈', 'Node.js', 'React'],
    isExternal: false,
  },
  {
    id: '10',
    name: '陈十二',
    avatar: '',
    title: '数据分析师',
    department: '数据部',
    phone: '+86 138-0123-4567',
    email: 'chenshier@example.com',
    status: 'away',
    isStarred: false,
    isManager: false,
    bio: '负责数据分析和业务洞察',
    tags: ['数据', '分析'],
    isExternal: false,
  },
  {
    id: '11',
    name: '林十三',
    avatar: '',
    title: 'HR经理',
    department: '人力资源部',
    phone: '+86 139-1234-5678',
    email: 'linshisan@example.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责人才招聘和员工关系管理',
    tags: ['HR', '招聘'],
    isExternal: false,
  },
  {
    id: '12',
    name: '黄十四',
    avatar: '',
    title: '财务总监',
    department: '财务部',
    phone: '+86 139-2345-6789',
    email: 'huangshisi@example.com',
    status: 'offline',
    isStarred: false,
    isManager: true,
    bio: '负责财务管理和成本控制',
    tags: ['财务', '管理'],
    isExternal: false,
  },
  {
    id: '13',
    name: '刘十五',
    avatar: '',
    title: '客户经理',
    department: '销售部',
    phone: '+86 139-3456-7890',
    email: 'liushiwu@example.com',
    status: 'online',
    isStarred: false,
    isManager: false,
    bio: '负责客户关系维护和销售',
    tags: ['销售', '客户'],
    isExternal: false,
  },
  {
    id: '14',
    name: '外部顾问A',
    avatar: '',
    title: '技术顾问',
    department: '外部',
    phone: '+86 139-4567-8901',
    email: 'consultant-a@external.com',
    status: 'offline',
    isStarred: false,
    isManager: false,
    bio: '提供技术咨询服务',
    tags: ['顾问', '外部'],
    isExternal: true,
  },
  {
    id: '15',
    name: '合作伙伴B',
    avatar: '',
    title: '商务经理',
    department: '外部',
    phone: '+86 139-5678-9012',
    email: 'partner-b@external.com',
    status: 'online',
    isStarred: true,
    isManager: false,
    bio: '战略合作伙伴',
    tags: ['合作', '外部'],
    isExternal: true,
  },
];
